### ISSUE TITLE
about using an I2S microphone

### ISSUE THREAD

**Issue by kittennbfive** [brian-smith-github/ch32v003_stt#1]
Hi,

i found your project on Hackaday. I did not use it but it looks impressive.

You say:
>No I2S support so using a higher-quality digital microphone is not an option.

I am not familiar with these CH32V003 devices, but briefly looking at the datasheet i see an SPI-port (at least for some variants, which one do you use?) and DMA for continuous operation, so *maybe* it is possible to (ab)use this to connect an I2S-mic as i did using the USART on an AVR ATmega328P:  https://github.com/kittennbfive/avr-i2s

I just wanted to share this idea, maybe you or somebody will make it work. My project uses assembly (and is AGPLv3+) so the code would need to be rewritten from scratch for the CH32V003.

Have a great day!

**Comment by brian-smith-github** [comment]
Hi there.
Believe me, I did try to do this already! the 'ch32v003fun' library examples include a demo of (ab)using the SPI and timers on the chip to simulate I2S to _output_ audio (spi_dac directory) - see:

https://github.com/cnlohr/ch32v003fun/blob/master/examples/spi_dac/README.md

I've already tried adapting the code (along with a MEMS mic) to read the SPI bus instead of writing to it, but I could never get it working properly for some reason, so in the end I gave up and went back to ADC. The ADC audio 'sounds' OK, albeit noisy, and I can feed it to 'proper' speech-to-text software and get accurate results, so just stuck with that in the end. 
Once the new version of the processor comes out (CH32V002, due any day now), I'll try again with that as it has more RAM and features.

**Comment by kittennbfive** [comment]
Hi,

sorry, i did not see this... My method was to use the SPI to both generate the master clock and the word clock (by transmitting 4\*0xff or 4\*0x00 alternating). I didn't use any timers. It worked but only in assembly, so yeah, tedious business...

Good luck if you try again! You can close this issue if you want.
